<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net481</TargetFramework>

        <OutputType>WinExe</OutputType>
        <UseWindowsForms>true</UseWindowsForms>

        <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
        <LangVersion>latest</LangVersion>
        <ApplicationIcon>Resources\icon.ico</ApplicationIcon>

        <Version>1.0.0.5</Version>
        <AssemblyVersion>$(Version)</AssemblyVersion>
        <FileVersion>$(Version)</FileVersion>

        <Description>JALib ModApplicator is A Dance of Fire and Ice mod applicator.</Description>
        <Company>Jongyeol</Company>
        <Copyright>Copyright © Jongyeol 2024-2026</Copyright>
    </PropertyGroup>
    
    <ItemGroup>
        <Reference Include="System.IO.Compression" />
        <Reference Include="System.Net.Http" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    </ItemGroup>
</Project>