<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net481</TargetFramework>
        <DisableImplicitFrameworkReferences>true</DisableImplicitFrameworkReferences>
        <AutomaticallyUseFrameworkAssemblies>false</AutomaticallyUseFrameworkAssemblies>
        <NoStdLib>true</NoStdLib>
        <AddAdditionalExplicitAssemblyReferences>false</AddAdditionalExplicitAssemblyReferences>

        <LangVersion>latest</LangVersion>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

        <DebugSymbols>true</DebugSymbols>
        <DebugType>portable</DebugType>

        <Version>1.0.0.10</Version>
        <AssemblyVersion>$(Version)</AssemblyVersion>
        <FileVersion>$(Version)</FileVersion>

        <Description>Jongyeol Adofai Library Bootstrap</Description>
        <Company>Jongyeol</Company>
        <Copyright>Copyright © Jongyeol 2024-2026</Copyright>
    </PropertyGroup>

    <Target Name="GetReferenceAssemblyPaths" />

    <PropertyGroup>
        <FrameworkPathOverride>$(GameManagedPath)</FrameworkPathOverride>
        <TargetFrameworkDirectory>$(GameManagedPath)</TargetFrameworkDirectory>
    </PropertyGroup>

    <ItemGroup>
        <Reference Include="0Harmony">
            <HintPath>$(GameManagedPath)\UnityModManager\0Harmony.dll</HintPath>
        </Reference>
        <Reference Include="JAMod.Bootstrap">
            <HintPath>..\JAMod.Bootstrap\obj\Release\JAMod.Bootstrap.dll</HintPath>
        </Reference>
        <Reference Include="mscorlib">
            <HintPath>$(GameManagedPath)\mscorlib.dll</HintPath>
        </Reference>
        <Reference Include="System">
            <HintPath>$(GameManagedPath)\System.dll</HintPath>
        </Reference>
        <Reference Include="System.IO.Compression">
            <HintPath>$(GameManagedPath)\System.IO.Compression.dll</HintPath>
        </Reference>
        <Reference Include="System.Net.Http">
            <HintPath>$(GameManagedPath)\System.Net.Http.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.CoreModule">
            <HintPath>$(GameManagedPath)\UnityEngine.CoreModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityModManager">
            <HintPath>$(GameManagedPath)\UnityModManager\UnityModManager.dll</HintPath>
        </Reference>
    </ItemGroup>

    <Target Name="CopyToModPath" AfterTargets="Build" Condition="'$(ModPath)' != ''">
        <Copy SourceFiles="$(OutputPath)JALib.Bootstrap.dll" DestinationFolder="$(ModPath)/JALib"/>
        <Copy SourceFiles="$(OutputPath)JALib.Bootstrap.pdb" DestinationFolder="$(ModPath)/JALib"/>
    </Target>

    <Target Name="CopyToReleasePath" AfterTargets="Build" Condition="'$(ReleasePath)' != '' and '$(Configuration)' == 'Release'">
        <Copy SourceFiles="bin/Release/JALib.Bootstrap.dll" DestinationFolder="$(ReleasePath)/JALib"/>
    </Target>
</Project>
